/*
 * Copyright (C)2020	Kai Ludwig, DG4KLU
 *               and	Roger Clark, VK3KYY / G4KYF
 *               and	Daniel Caujolle-Bert, F1RMB
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 */

#ifndef _EPL003_H_
#define _EPL003_H_

#include <common.h>


#if defined(PLATFORM_GD77S)

#define Port_SpeechSynth_CLK   PORTC
#define GPIO_SpeechSynth_CLK   GPIOC
#define Pin_SpeechSynth_CLK    11

#define Port_SpeechSynth_DAT   PORTC
#define GPIO_SpeechSynth_DAT   GPIOC
#define Pin_SpeechSynth_DAT    12


typedef enum
{
	SPEECH_SYNTHESIS_ZERO = 0,
	SPEECH_SYNTHESIS_ONE = 1,
	SPEECH_SYNTHESIS_TWO = 2,
	SPEECH_SYNTHESIS_THREE = 3,
	SPEECH_SYNTHESIS_FOUR = 4,
	SPEECH_SYNTHESIS_FIVE = 5,
	SPEECH_SYNTHESIS_SIX = 6,
	SPEECH_SYNTHESIS_SEVEN = 7,
	SPEECH_SYNTHESIS_HEIGHT = 8,
	SPEECH_SYNTHESIS_NINE = 9,
	SPEECH_SYNTHESIS_TEN = 10,
	SPEECH_SYNTHESIS_ELEVEN = 11,
	SPEECH_SYNTHESIS_TWELVE = 12,
	SPEECH_SYNTHESIS_THIRTEEN = 13,
	SPEECH_SYNTHESIS_FOURTEEN = 14,
	SPEECH_SYNTHESIS_FIFTEEN = 15,
	SPEECH_SYNTHESIS_SIXTEEN = 16,
	SPEECH_SYNTHESIS_SEVENTEEN = 17,
	SPEECH_SYNTHESIS_HEIGHTEEN = 18,
	SPEECH_SYNTHESIS_NINETEEN = 19,
	SPEECH_SYNTHESIS_TWENTY = 20,
	SPEECH_SYNTHESIS_THIRTY = 21,
	SPEECH_SYNTHESIS_FOURTY = 22,
	SPEECH_SYNTHESIS_FIFTY = 23,
	SPEECH_SYNTHESIS_SIXTY = 24,
	SPEECH_SYNTHESIS_SEVENTY = 25,
	SPEECH_SYNTHESIS_EIGHTY = 26,
	SPEECH_SYNTHESIS_NINETY = 27,
	SPEECH_SYNTHESIS_HUNDRED = 28,
	SPEECH_SYNTHESIS_POWER_ON = 29,
	SPEECH_SYNTHESIS_PLEASE_CHARGE_THE_BATTERY = 30,
	SPEECH_SYNTHESIS_CLONING = 31,
	SPEECH_SYNTHESIS_POWER_OFF = 32,
	SPEECH_SYNTHESIS_ALARM = 33,
	SPEECH_SYNTHESIS_SQUELCH = 34,
	SPEECH_SYNTHESIS_VOX = 35,
	SPEECH_SYNTHESIS_LEVEL = 36,
	SPEECH_SYNTHESIS_SCRAMBLE = 37,
	SPEECH_SYNTHESIS_SCAN = 38,
	SPEECH_SYNTHESIS_ON = 39,
	SPEECH_SYNTHESIS_OFF = 40,
	SPEECH_SYNTHESIS_FREQUENCY = 41,
	SPEECH_SYNTHESIS_CHANNEL = 42,
	SPEECH_SYNTHESIS_POWER = 43,
	SPEECH_SYNTHESIS_KEY = 44,
	SPEECH_SYNTHESIS_LOCK = 45,
	SPEECH_SYNTHESIS_UNLOCK = 46,
	SPEECH_SYNTHESIS_MODE = 47,
	SPEECH_SYNTHESIS_SHIFT = 48,
	SPEECH_SYNTHESIS_PLUS = 49,
	SPEECH_SYNTHESIS_MINUS = 50,
	SPEECH_SYNTHESIS_REVERSE = 51,
	SPEECH_SYNTHESIS_PRIORITY = 52,
	SPEECH_SYNTHESIS_TONE = 53,
	SPEECH_SYNTHESIS_RECEIVE = 54,
	SPEECH_SYNTHESIS_TRANSMIT = 55,
	SPEECH_SYNTHESIS_STORE = 56,
	SPEECH_SYNTHESIS_ID_CODE = 57,
	SPEECH_SYNTHESIS_CTCSS = 58,
	SPEECH_SYNTHESIS_DCS = 59,
	SPEECH_SYNTHESIS_DTMF = 60,
	SPEECH_SYNTHESIS_STEP = 61,
	SPEECH_SYNTHESIS_WIDE = 62,
	SPEECH_SYNTHESIS_NARROW = 63,
	SPEECH_SYNTHESIS_LIGHT = 64,
	SPEECH_SYNTHESIS_MENU = 65,
	SPEECH_SYNTHESIS_FUNCTION = 66,
	SPEECH_SYNTHESIS_SET = 67,
	SPEECH_SYNTHESIS_NAME = 68,
	SPEECH_SYNTHESIS_EXIT = 69,
	SPEECH_SYNTHESIS_ERROR = 70,
	SPEECH_SYNTHESIS_AUTO = 71,
	SPEECH_SYNTHESIS_OKAY = 72,
	SPEECH_SYNTHESIS_ENTER = 73,
	SPEECH_SYNTHESIS_DELETE = 74,
	SPEECH_SYNTHESIS_HIGH = 75,
	SPEECH_SYNTHESIS_MIDDLE = 76,
	SPEECH_SYNTHESIS_LOW = 77,
	SPEECH_SYNTHESIS_BATTERY = 78,
	SPEECH_SYNTHESIS_POINT = 79,
	SPEECH_SYNTHESIS_SAVE = 80,
	SPEECH_SYNTHESIS_RADIO = 81,
	SPEECH_SYNTHESIS_T_O_T = 82,
	SPEECH_SYNTHESIS_REVERSE_FUNCTION = 83,
	SPEECH_SYNTHESIS_COMM_PENDING = 84,
	SPEECH_SYNTHESIS_WHISPER = 85,
	SPEECH_SYNTHESIS_TONE_DUPLICATE = 86, // Duplicate in IC
	SPEECH_SYNTHESIS_END = 87,
	SPEECH_SYNTHESIS_SEQUENCE_SEPARATOR = 88, // Does not exist in the IC, used as a gap
	SPEECH_SYNTHESIS_DISPLAY_COLOR = 89,
	SPEECH_SYNTHESIS_ORANGE = 90,
	SPEECH_SYNTHESIS_GREEN = 91,
	SPEECH_SYNTHESIS_BLUE = 92,
	SPEECH_SYNTHESIS_RED = 93,
	SPEECH_SYNTHESIS_YELLOW = 94,
	SPEECH_SYNTHESIS_PURPLE = 95,
	SPEECH_SYNTHESIS_WHITE = 96
} EPL003_Sequence_t;


void EPL003_init(void);
void EPL003_speak(EPL003_Sequence_t seq);

#endif

#endif /* _EPL003_H_ */
