/*
 * Copyright (C)2019 Roger Clark. VK3KYY / G4KYF
 *
 * Using some code ported from MMDVM_HS by Andy CA6JAU
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 */

#include <user_interface/uiLocalisation.h>

const stringsTable_t englishLanguage =
{
.LANGUAGE_NAME 		= "English",
.language			= "Language",
.menu				= "Menu",
.credits			= "Credits",
.zone				= "Zone",
.rssi				= "RSSI",
.battery			= "Battery",
.contacts			= "Contacts",
.firmware_info		= "Firmware info",
.last_heard			= "Last heard",
.options			= "Options",
.display_options	= "Display options",
.channel_details	= "Channel details",
.new_contact		= "New contact",
.contact_list		= "Contact list",
.hotspot_mode		= "Hotspot mode",
.contact_details	= "Contact Details",
.batteryVoltage		= "%d.%dV",
.built				= "Built",
.built				= "Built",
.zones				= "Zones",
.keypad_locked		= "Keypad locked",
.press_blue_plus_star	= "Press Blue +*",
.to_unlock			= "to unlock",
.unlocked			= "Unlocked",
.power_off			= "Power Off...",
.error				= "ERROR",
.rx_only			= "Rx only",
.out_of_band		= "OUT OF BAND",
.timeout			= "TIMEOUT",
.tg_entry			= "TG entry",
.pc_entry			= "PC entry",
.user_dmr_id		= "User DMR ID",
.contact 			= "Contact",
.displayRxFreq		= "%d.%05d MHz",
.accept_call		=  "Accept call?",
.private_call		= "Private call",
.squelch			= "Squelch",
.vfoRxFreq			= "%cR %d.%05d MHz",
.vfoTxFreq			= "%cT %d.%05d MHz",
.vfoEnterFreq		= "%c%c%c.%c%c%c%c%c MHz",
.quick_menu 		= "Quick Menu",
.filter				= "Filter:%s",
.all_channels		= "All Channels",
.gotoChannel		= "Goto %d",
.scan				= "Scan",
.channelToVfo		= "Channel --> VFO",
.vfoToChannel		= "VFO --> Channel",
.group				= "Group",
.private			= "Private",
.all				= "All",
.type				= "Type:",
.timeSlot			= "Timeslot",
.none				= "none",
.contact_saved		= "Contact saved",
.duplicate			=  "Duplicate",
.tg					= "TG",
.pc					= "PC",
.ts					= "TS",
.mode				= "Mode",
.colour_code		= "Color Code",
.n_a				= "N/A",
.channelDetailsRx	= "Rx:%d.%05dMHz",
.channelDetailsTx	= "Tx:%d.%05dMHz",
.bandwidth			= "Bandwidth",
.stepFreq				= "Step:%d.%02dkHz",
.tot				= "TOT",
.off				= "Off",
.skip				= "Skip",
.yes				= "Yes",
.no					= "No",
.rx_group			= "Rx Grp",
};

const stringsTable_t frenchLanguage =
{
.LANGUAGE_NAME 		= "French",
.language			= "Language",
.menu				= "Menu",
.credits			= "Credits",
.zone				= "Zone",
.rssi				= "RSSI",
.battery			= "Battery",
.contacts			= "Contacts",
.firmware_info		= "Firmware info",
.last_heard			= "Last heard",
.options			= "Options",
.display_options	= "Display options",
.channel_details	= "Channel details",
.new_contact		= "New contact",
.contact_list		= "Contact list",
.hotspot_mode		= "Hotspot mode",
.contact_details	= "Contact Details",
.batteryVoltage		= "%d,%dV",
.built				= "Built",
.built				= "Built",
.zones				= "Zones",
.keypad_locked		= "Keypad locked",
.press_blue_plus_star	= "Press Blue +*",
.to_unlock			= "to unlock",
.unlocked			= "Unlocked",
.power_off			= "Power Off...",
.error				= "ERROR",
.rx_only			= "Rx only",
.out_of_band		= "OUT OF BAND",
.timeout			= "TIMEOUT",
.tg_entry			= "TG entry",
.pc_entry			= "PC entry",
.user_dmr_id		= "User DMR ID",
.contact 			= "Contact",
.displayRxFreq		= "%d.%05d MHz",
.accept_call		=  "Accept call?",
.private_call		= "Private call",
.squelch			= "Squelch",
.vfoRxFreq			= "%cR %d,%05d MHz",
.vfoTxFreq			= "%cT %d,%05d MHz",
.vfoEnterFreq		= "%c%c%c.%c%c%c%c%c MHz",
.quick_menu 		= "Quick Menu",
.filter				= "Filter:%s",
.all_channels		= "All Channels",
.gotoChannel		= "Goto %d",
.scan				= "Scan",
.channelToVfo		= "Channel --> VFO",
.vfoToChannel		= "VFO --> Channel",
.group				= "Group",
.private			= "Private",
.all				= "All",
.type				= "Type:",
.timeSlot			= "Timeslot",
.none				= "none",
.contact_saved		= "Contact saved",
.duplicate			=  "Duplicate",
.tg					= "TG",
.pc					= "PC",
.ts					= "TS",
.mode				= "Mode",
.colour_code		= "Color Code",
.n_a				= "N/A",
.channelDetailsRx	= "Rx:%d,%05dMHz",
.channelDetailsTx	= "Tx:%d,%05dMHz",
.bandwidth			= "Bandwidth",
.stepFreq				= "Step:%d.%02dkHz",
.tot				= "TOT",
.off				= "Off",
.skip				= "Skip",
.yes				= "Yes",
.no					= "No",
.rx_group			= "Rx Grp",
};


const stringsTable_t germanLanguage =
{
.LANGUAGE_NAME 		= "German",
.language			= "Language",
.menu				= "Menu",
.credits			= "Credits",
.zone				= "Zone",
.rssi				= "RSSI",
.battery			= "Battery",
.contacts			= "Contacts",
.firmware_info		= "Firmware info",
.last_heard			= "Last heard",
.options			= "Options",
.display_options	= "Display options",
.channel_details	= "Channel details",
.new_contact		= "New contact",
.contact_list		= "Contact list",
.hotspot_mode		= "Hotspot mode",
.contact_details	= "Contact Details",
.batteryVoltage		= "%d.%dV",
.built				= "Built",
.built				= "Built",
.zones				= "Zones",
.keypad_locked		= "Keypad locked",
.press_blue_plus_star	= "Press Blue +*",
.to_unlock			= "to unlock",
.unlocked			= "Unlocked",
.power_off			= "Power Off...",
.error				= "ERROR",
.rx_only			= "Rx only",
.out_of_band		= "OUT OF BAND",
.timeout			= "TIMEOUT",
.tg_entry			= "TG entry",
.pc_entry			= "PC entry",
.user_dmr_id		= "User DMR ID",
.contact 			= "Contact",
.displayRxFreq		= "%d.%05d MHz",
.accept_call		=  "Accept call?",
.private_call		= "Private call",
.squelch			= "Squelch",
.vfoRxFreq			= "%cR %d.%05d MHz",
.vfoTxFreq			= "%cT %d.%05d MHz",
.vfoEnterFreq		= "%c%c%c.%c%c%c%c%c MHz",
.quick_menu 		= "Quick Menu",
.filter				= "Filter:%s",
.all_channels		= "All Channels",
.gotoChannel		= "Goto %d",
.scan				= "Scan",
.channelToVfo		= "Channel --> VFO",
.vfoToChannel		= "VFO --> Channel",
.group				= "Group",
.private			= "Private",
.all				= "All",
.type				= "Type:",
.timeSlot			= "Timeslot",
.none				= "none",
.contact_saved		= "Contact saved",
.duplicate			=  "Duplicate",
.tg					= "TG",
.pc					= "PC",
.ts					= "TS",
.mode				= "Mode",
.colour_code		= "Color Code",
.n_a				= "N/A",
.channelDetailsRx	= "Rx:%d.%05dMHz",
.channelDetailsTx	= "Tx:%d.%05dMHz",
.bandwidth			= "Bandwidth",
.stepFreq				= "Step:%d.%02dkHz",
.tot				= "TOT",
.off				= "Off",
.skip				= "Skip",
.yes				= "Yes",
.no					= "No",
.rx_group			= "Rx Grp",
};

const stringsTable_t languages[NUM_LANGUAGES]= { englishLanguage ,frenchLanguage,germanLanguage};

const stringsTable_t *currentLanguage = &languages[0];

stringsTable_t *lang;
