/*
 * Copyright (C)2019 Roger Clark. VK3KYY / G4KYF
 *
 * Using some code ported from MMDVM_HS by Andy CA6JAU
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 */

#include <user_interface/uiLocalisation.h>

const stringsTable_t englishLanguage =
{
.LANGUAGE_NAME 		= "English",
.language			= "Language",
.menu				= "Menu",
.credits			= "Credits",
.zone				= "Zone",
.rssi				= "RSSI",
.battery			= "Battery",
.contacts			= "Contacts",
.firmware_info		= "Firmware info",
.last_heard			= "Last heard",
.options			= "Options",
.display_options	= "Display options",
.channel_details	= "Channel details",
.new_contact		= "New contact",
.contact_list		= "Contact list",
.hotspot_mode		= "Hotspot mode",
.contact_details	= "Contact Details",
.batteryVoltage		= "%d.%dV",
.built				= "Built",
.built				= "Built",
.zones				= "Zones",
.keypad_locked		= "Keypad locked",
.press_blue_plus_star	= "Press Blue +*",
.to_unlock			= "to unlock",
.unlocked			= "Unlocked",
.power_off			= "Power Off...",
.error				= "ERROR",
.rx_only			= "Rx only",
.out_of_band		= "OUT OF BAND",
.timeout			= "TIMEOUT",
.tg_entry			= "TG entry",
.pc_entry			= "PC entry",
.user_dmr_id		= "User DMR ID",
.contact 			= "Contact",
.displayRxFreq		= "%d.%05d MHz",
.accept_call		=  "Accept call?",
.private_call		= "Private call",
.squelch			= "Squelch",
.vfoRxFreq			= "%cR %d.%05d MHz",
.vfoTxFreq			= "%cT %d.%05d MHz",
.vfoEnterFreq		= "%c%c%c.%c%c%c%c%c MHz",
.quick_menu 		= "Quick Menu",
.filter				= "Filter:%s",
.all_channels		= "All Channels",
.gotoChannel		= "Goto %d",
.scan				= "Scan",
.channelToVfo		= "Channel --> VFO",
.vfoToChannel		= "VFO --> Channel",
.group				= "Group",
.private			= "Private",
.all				= "All",
.type				= "Type:",
.timeSlot			= "Timeslot",
.none				= "none",
.contact_saved		= "Contact saved",
.duplicate			=  "Duplicate",
.tg					= "TG",
.pc					= "PC",
.ts					= "TS",
.mode				= "Mode",
.colour_code		= "Color Code",
.n_a				= "N/A",
.channelDetailsRx	= "Rx:%d.%05dMHz",
.channelDetailsTx	= "Tx:%d.%05dMHz",
.bandwidth			= "Bandwidth",
.stepFreq				= "Step:%d.%02dkHz",
.tot				= "TOT",
.off				= "Off",
.skip				= "Skip",
.yes				= "Yes",
.no					= "No",
.rx_group			= "Rx Grp",
};


const stringsTable_t germanLanguage =
{
.LANGUAGE_NAME 		= "Deutsch",
.language			= "Sprache",
.menu				= "Menu",
.credits			= "Mitwirkende",
.zone				= "Zone",
.rssi				= "Feldstarke",
.battery			= "Batterie",
.contacts			= "Kontakte",
.firmware_info		= "Firmware Info",
.last_heard			= "Zuletzt gehort",
.options			= "Einstellungen",
.display_options	= "Display Optionen",
.channel_details	= "Kanal Details",
.new_contact		= "Neuer Kontakt",
.contact_list		= "Kontaktliste",
.hotspot_mode		= "Hotspot-Modus",
.contact_details	= "Kontakt Details",
.batteryVoltage		= "%d.%dV",
.built				= "Erstellt",
.built				= "Erstellt",
.zones				= "Zonen",
.keypad_locked		= "Tasten gesperrt",
.press_blue_plus_star	= "Blaue Taste +*",
.to_unlock			= "zum entsperren",
.unlocked			= "Entsperrt",
.power_off			= "Schalte aus...",
.error				= "FEHLER",
.rx_only			= "Nur Rx",
.out_of_band		= "AUSSER BAND",
.timeout			= "Zeit abgelaufen",
.tg_entry			= "TG Eingabe",
.pc_entry			= "PC Eingabe",
.user_dmr_id		= "Benutzer ID",
.contact 			= "Kontakt",
.displayRxFreq		= "%d.%05d MHz",
.accept_call		= "Ruf annehmen?",
.private_call		= "Privater Ruf",
.squelch			= "Rauschsperre",
.vfoRxFreq			= "%cR %d.%05d MHz",
.vfoTxFreq			= "%cT %d.%05d MHz",
.vfoEnterFreq		= "%c%c%c.%c%c%c%c%c MHz",
.quick_menu 		= "Schnell Menü",
.filter				= "Filter:%s",
.all_channels		= "Alle Kanäle",
.gotoChannel		= "Gehe zu %d",
.scan				= "Scan",
.channelToVfo		= "Kanal --> VFO",
.vfoToChannel		= "VFO --> Kanal",
.group				= "Gruppe",
.private			= "Privat",
.all				= "Alle",
.type				= "Type:",
.timeSlot			= "Zeitschlitz",
.none				= "kein",
.contact_saved		= "Kontakt gesp.",
.duplicate			=  "Duplikat",
.tg					= "TG",
.pc					= "PC",
.ts					= "TS",
.mode				= "Modus",
.colour_code		= "Color Code",
.n_a				= "N/A",
.channelDetailsRx	= "Rx:%d.%05dMHz",
.channelDetailsTx	= "Tx:%d.%05dMHz",
.bandwidth			= "Bandbreite",
.stepFreq			= "Step:%d.%02dkHz",
.tot				= "TOT",
.off				= "Aus",
.skip				= "Überspringen",
.yes				= "Ja",
.no					= "Nein",
.rx_group			= "Rx Gruppe",
};

const stringsTable_t portuguesLanguage =
{
.LANGUAGE_NAME 		= "Portugues",
.language			= "Lingua",
.menu				= "Menu",
.credits			= "Creditos",
.zone				= "Zona",
.rssi				= "RSSI",
.battery			= "Bateria",
.contacts			= "Contactos",
.firmware_info		= "Versao Firmware",
.last_heard			= "Ultima escutada",
.options			= "Opcoes",
.display_options	= "Opcoes Visor",
.channel_details	= "Detalhes Canal",
.new_contact		= "Contacto Novo",
.contact_list		= "Lista Contactos",
.hotspot_mode		= "Modo Hotspot",
.contact_details	= "Detalhes Contato",
.batteryVoltage		= "%d.%dV",
.built				= "Built",
.built				= "Built",
.zones				= "Zonas",
.keypad_locked		= "TecladoBloqueado",
.press_blue_plus_star="Prima Azul + *",
.to_unlock			= "Para Desbloquear",
.unlocked			= "Desbloqueado",
.power_off			= "Desligar...",
.error				= "ERRO",
.rx_only			= "Apenas Rx",
.out_of_band		= "FORA DA BANDA",
.timeout			= "TEMPO ESGOTADO",
.tg_entry			= "Entrada TG",
.pc_entry			= "Entrada PC",
.user_dmr_id		= "DMRID Utilizador",
.contact 			= "Contacto",
.displayRxFreq		= "%d.%05d MHz",
.accept_call		= "Aceitar Chamada?",
.private_call		= "Chamada Privada",
.squelch			= "Squelch",
.vfoRxFreq			= "%cR %d.%05d MHz",
.vfoTxFreq			= "%cT %d.%05d MHz",
.vfoEnterFreq		= "%c%c%c.%c%c%c%c%c MHz",
.quick_menu 		= "Menu Rápido",
.filter				= "Filtro:%s",
.all_channels		= "Todos os Canais",
.gotoChannel		= "Ir para %d",
.scan				= "Busca",
.channelToVfo		= "Canal --> VFO",
.vfoToChannel		= "VFO --> Canal",
.group				= "Grupo",
.private			= "Privado",
.all				= "Todos",
.type				= "Tipo:",
.timeSlot			= "Intervalo Tempo",
.none				= "Nenhum",
.contact_saved		= "Contacto Gravado",
.duplicate			= "Duplicado",
.tg					= "TG",
.pc					= "PC",
.ts					= "TS",
.mode				= "Mode",
.colour_code		= "Codigo de cores",
.n_a				= "N/A",
.channelDetailsRx	= "Rx:%d.%05dMHz",
.channelDetailsTx	= "Tx:%d.%05dMHz",
.bandwidth			= "Largura de banda",
.stepFreq			= "Passo:%d.%02dkHz",
.tot				= "TOT",
.off				= "Off",
.skip				= "Ignorar",
.yes				= "Sim",
.no					= "Nao",
.rx_group			= "Rx Grp",
};

const stringsTable_t languages[NUM_LANGUAGES]= { englishLanguage ,germanLanguage,portuguesLanguage};
const stringsTable_t *currentLanguage;
